import { AgentReport, ScanCoverage } from "./types.js";
import { TriagedScanResult } from "./scout.js";

export function coverageSpan(c: ScanCoverage): number | null {
  if (!c.startCheckpoint || !c.endCheckpoint) return null;
  return Number(BigInt(c.endCheckpoint) - BigInt(c.startCheckpoint) + 1n);
}

export function coverageCaveat(c: ScanCoverage): string {
  const problems: string[] = [];
  if (!c.complete) problems.push("a listing stopped before the checkpoint bound");
  if (c.txsErrored > 0) problems.push(`${c.txsErrored} transactions failed to analyze`);

  const unreached = c.txsListed - c.txsAnalyzed - c.txsSkipped - c.txsErrored;
  if (unreached > 0) problems.push(`${unreached} of ${c.txsListed} listed txs not reached`);

  if (problems.length === 0) {
    return "complete — every listed transaction reached, to the checkpoint bound";
  }
  return `INCOMPLETE — ${problems.join("; ")}`;
}

export function toMarkdown(report: AgentReport): string {
  const lines: string[] = [];

  lines.push(`# Chase Hunt Report`);
  lines.push(``);
  lines.push(`**Target:** \`${report.mandate.target}\``);
  lines.push(`**Goal:** ${report.mandate.goal}`);
  const c = report.coverage;
  lines.push(`**Scope:** ${report.mandate.checkpoints} checkpoints per pass × ${c.passes} passes`);
  const span = coverageSpan(c);
  const counted = [`${c.txsListed} txs listed`, `${c.txsAnalyzed} analyzed`];
  if (c.txsSkipped > 0) counted.push(`${c.txsSkipped} system txs skipped`);
  if (c.txsCarried > 0) counted.push(`${c.txsCarried} already seen`);
  if (c.txsErrored > 0) counted.push(`${c.txsErrored} failed`);
  lines.push(
    `**Covered:** seq ${c.startCheckpoint ?? "n/a"}–${c.endCheckpoint ?? "n/a"} (${span ?? 0} checkpoints wide) · ${counted.join(" · ")}`
  );
  lines.push(`**Coverage:** ${coverageCaveat(c)}`);
  if (c.controlTraffic === "traffic-in-range") {
    lines.push(
      `**Control:** the filtered listing matched nothing, yet the same range does contain transactions — the target was not reached by a top-level MoveCall here.`
    );
  } else if (c.controlTraffic === "no-traffic-in-range") {
    lines.push(
      `**Control:** the same range holds no transactions even unfiltered — an endpoint or range problem, not a clean result.`
    );
  }
  lines.push(`**Started:** ${report.startedAt}`);
  lines.push(`**Duration:** ${report.usage.elapsedMs}ms`);
  lines.push(``);

  lines.push(`## Usage`);
  lines.push(``);
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| RPC calls | ${report.usage.rpcCalls} |`);
  lines.push(`| LLM calls | ${report.usage.llmCalls} |`);
  lines.push(`| Tokens | ${report.usage.llmTokens} |`);
  lines.push(``);

  lines.push(`## Decisions`);
  lines.push(``);
  if (report.decisions.length === 0) {
    lines.push(`No decisions recorded.`);
  } else {
    for (const d of report.decisions) {
      lines.push(
        `- **${d.action}${d.degraded ? " [DEGRADED — not a model decision]" : ""}**: ${d.reason}`
      );
    }
  }
  lines.push(``);

  lines.push(`## Findings (${report.findings.length})`);
  lines.push(``);

  if (report.findings.length === 0) {
    lines.push(`No findings.`);
  } else {
    const triaged = report.findings as TriagedScanResult[];
    for (const f of triaged) {
      lines.push(`### \`${f.digest}\``);
      lines.push(``);
      lines.push(`- **Checkpoint:** ${f.checkpoint}`);
      if (f.tier) lines.push(`- **Tier:** ${f.tier}`);
      if (f.action) lines.push(`- **Recommended action:** ${f.action}`);
      if (typeof f.score === "number") lines.push(`- **Score:** ${f.score}`);
      if (f.tierError) lines.push(`- **Triage problem:** ${f.tierError}`);
      if (f.investigationError) lines.push(`- **Investigation problem:** ${f.investigationError}`);
      if (f.investigation) {
        lines.push(`- **Investigator:** ${f.investigation.verdict}`);
        if (f.investigation.reasoning) {
          lines.push(`  - ${f.investigation.reasoning}`);
        }
      }
      lines.push(``);
      for (const v of f.violations) {
        lines.push(`- **${v.severity.toUpperCase()}** ${v.type} — ${v.message}`);
      }
      lines.push(``);
    }
  }

  lines.push(`## Summary`);
  lines.push(``);
  if (report.summaryDegraded) {
    lines.push(`_(generated by the fallback path, not by the configured model)_`);
    lines.push(``);
  }
  lines.push(report.summary);
  lines.push(``);

  return lines.join("\n");
}
